[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "django-client-side"
version = "0.1.0"
description = "Simple client-side dependency management for your django project."
readme = "README.md"
authors = [
    {name = "powderflask", email = "powderflask@gmail.com"}
]
maintainers = [
    {name = "powderflask", email = "powderflask@gmail.com"}
]
license = "MIT"
homepage = "https://github.com/powderflask/django-client-side"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Framework :: Django",
]
requires-python = ">=3.6"
dynamic = ["django"
]

[project.urls]
Homepage = "https://github.com/powderflask/django-client-side"

[project.scripts]
# Add your scripts here

[project.dependencies]
# Add your dependencies here

[project.optional-dependencies]
# Add your optional dependencies here
