[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "django-client-side"
version = "0.1.0"
description = "Simple client-side dependency management for your django project."
readme = "README.md"
authors = [
    {name = "powderflask", email = "powderflask@gmail.com"}
]
maintainers = [
    {name = "powderflask", email = "powderflask@gmail.com"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Framework :: Django",
]
requires-python = ">=3.6"

dependencies = [
    'django >= 2.0',
    'setuptools >= 65.5.1',
]

[project.optional-dependencies]
documentation = [
    'sphinx ==6.2.1',
    'livereload ==2.6.3',
    'myst-parser ==1.0.0'
    ]

[project.urls]
Homepage = "https://github.com/powderflask/django-client-side"
Repository = "https://github.com/powderflask/django-client-side"

[project.scripts]
"manage.py" = "django_client_side:django_manage"

